export const CATEGORIES = [
  { id: 'all', name: 'Усе', emoji: '🍽️' },
  { id: 'burgers', name: 'Бургери', emoji: '🍔' },
  { id: 'pizza', name: 'Піца', emoji: '🍕' },
  { id: 'sushi', name: 'Суші', emoji: '🍣' },
  { id: 'soups', name: 'Супи', emoji: '🍜' },
  { id: 'salads', name: 'Салати', emoji: '🥗' },
  { id: 'desserts', name: 'Десерти', emoji: '🍰' },
  { id: 'drinks', name: 'Напої', emoji: '🥤' },
];

export const MENU_ITEMS = [
  // BURGERS
  {
    id: '1',
    name: 'Класичний чізбургер',
    category: 'burgers',
    emoji: '🍔',
    price: 165,
    oldPrice: 195,
    rating: 4.8,
    reviews: 342,
    time: '15-20 хв',
    calories: 520,
    weight: '280 г',
    description: 'Соковита яловича котлета, плавлений чеддер, свіжі овочі та фірмовий соус на підсмаженій булочці бріош.',
    ingredients: ['Яловичина', 'Чеддер', 'Салат', 'Томат', 'Цибуля', 'Фірмовий соус', 'Булочка бріош'],
    isPopular: true,
    isNew: false,
    badge: 'Хіт',
  },
  {
    id: '2',
    name: 'Crispy Chicken Burger',
    category: 'burgers',
    emoji: '🍗',
    price: 175,
    oldPrice: null,
    rating: 4.7,
    reviews: 218,
    time: '15-25 хв',
    calories: 480,
    weight: '300 г',
    description: 'Хрустке куряче філе в паніровці, coleslaw, солені огірки та медово-гірчичний соус.',
    ingredients: ['Куряче філе', 'Капуста', 'Морква', 'Солоний огірок', 'Медово-гірчичний соус', 'Булочка'],
    isPopular: true,
    isNew: false,
    badge: null,
  },
  {
    id: '3',
    name: 'Смоки BBQ Бургер',
    category: 'burgers',
    emoji: '🥩',
    price: 195,
    oldPrice: null,
    rating: 4.9,
    reviews: 189,
    time: '15-25 хв',
    calories: 610,
    weight: '320 г',
    description: 'Подвійна котлета, бекон, карамелізована цибуля, соус BBQ та хрусткі цибулеві кільця.',
    ingredients: ['Яловичина x2', 'Бекон', 'Карамелізована цибуля', 'Соус BBQ', 'Цибулеві кільця', 'Чеддер'],
    isPopular: false,
    isNew: true,
    badge: 'Новинка',
  },
  {
    id: '4',
    name: 'Веганський бургер',
    category: 'burgers',
    emoji: '🥦',
    price: 155,
    oldPrice: null,
    rating: 4.5,
    reviews: 97,
    time: '15-20 хв',
    calories: 380,
    weight: '260 г',
    description: 'Котлета з нуту та буряку, авокадо, шпинат, томати та веганський майонез.',
    ingredients: ['Нут', 'Буряк', 'Авокадо', 'Шпинат', 'Томат', 'Веганський майонез'],
    isPopular: false,
    isNew: false,
    badge: 'Веган',
  },

  // PIZZA
  {
    id: '5',
    name: 'Маргарита',
    category: 'pizza',
    emoji: '🍕',
    price: 220,
    oldPrice: 260,
    rating: 4.9,
    reviews: 501,
    time: '20-30 хв',
    calories: 750,
    weight: '500 г',
    description: 'Класична неаполітанська піца з томатним соусом сан-марзано, моцарелою фіор ді лате та свіжим базиліком.',
    ingredients: ['Тісто', 'Томатний соус', 'Моцарела', 'Базилік', 'Оливкова олія'],
    isPopular: true,
    isNew: false,
    badge: 'Хіт',
  },
  {
    id: '6',
    name: 'Пепероні',
    category: 'pizza',
    emoji: '🌶️',
    price: 255,
    oldPrice: null,
    rating: 4.8,
    reviews: 430,
    time: '20-30 хв',
    calories: 890,
    weight: '550 г',
    description: 'Рясний шар гострого пепероні, моцарела та томатний соус на хрусткому тісті.',
    ingredients: ['Тісто', 'Томатний соус', 'Моцарела', 'Пепероні', 'Орегано'],
    isPopular: true,
    isNew: false,
    badge: null,
  },
  {
    id: '7',
    name: 'Чотири сири',
    category: 'pizza',
    emoji: '🧀',
    price: 275,
    oldPrice: null,
    rating: 4.7,
    reviews: 312,
    time: '20-30 хв',
    calories: 920,
    weight: '560 г',
    description: 'Ніжна піца з чотирма видами сиру: моцарела, горгонзола, пармезан та таледжо.',
    ingredients: ['Тісто', 'Моцарела', 'Горгонзола', 'Пармезан', 'Таледжо'],
    isPopular: false,
    isNew: false,
    badge: null,
  },
  {
    id: '8',
    name: 'Барбекю Чикен',
    category: 'pizza',
    emoji: '🍗',
    price: 265,
    oldPrice: null,
    rating: 4.6,
    reviews: 278,
    time: '20-30 хв',
    calories: 860,
    weight: '540 г',
    description: 'Куряче філе, соус BBQ, червона цибуля, болгарський перець та моцарела.',
    ingredients: ['Тісто', 'Соус BBQ', 'Куряче філе', 'Червона цибуля', 'Болгарський перець', 'Моцарела'],
    isPopular: false,
    isNew: true,
    badge: 'Новинка',
  },

  // SUSHI
  {
    id: '9',
    name: 'Філадельфія Roll',
    category: 'sushi',
    emoji: '🍣',
    price: 285,
    oldPrice: 320,
    rating: 4.9,
    reviews: 612,
    time: '25-35 хв',
    calories: 340,
    weight: '280 г',
    description: 'Класичний рол з лососем, вершковим сиром та огірком. 8 шт.',
    ingredients: ['Рис', 'Лосось', 'Вершковий сир', 'Огірок', 'Норі', 'Кунжут'],
    isPopular: true,
    isNew: false,
    badge: 'Хіт',
  },
  {
    id: '10',
    name: 'Каліфорнія Roll',
    category: 'sushi',
    emoji: '🦀',
    price: 245,
    oldPrice: null,
    rating: 4.7,
    reviews: 389,
    time: '25-35 хв',
    calories: 290,
    weight: '260 г',
    description: 'Крабове м\'ясо, авокадо та огірок в рисі та тобіко. 8 шт.',
    ingredients: ['Рис', 'Краб', 'Авокадо', 'Огірок', 'Тобіко', 'Кунжут'],
    isPopular: true,
    isNew: false,
    badge: null,
  },
  {
    id: '11',
    name: 'Дракон Roll',
    category: 'sushi',
    emoji: '🐉',
    price: 320,
    oldPrice: null,
    rating: 4.8,
    reviews: 201,
    time: '25-35 хв',
    calories: 410,
    weight: '300 г',
    description: 'Гострий тунець всередині, авокадо зовні з соусом унагі. 8 шт.',
    ingredients: ['Рис', 'Тунець', 'Авокадо', 'Соус унагі', 'Сезам', 'Норі'],
    isPopular: false,
    isNew: true,
    badge: 'Новинка',
  },

  // SOUPS
  {
    id: '12',
    name: 'Борщ з пампушками',
    category: 'soups',
    emoji: '🥣',
    price: 135,
    oldPrice: null,
    rating: 4.9,
    reviews: 789,
    time: '10-15 хв',
    calories: 320,
    weight: '400 г',
    description: 'Традиційний український борщ з м\'ясом, свіжою сметаною та часниковими пампушками.',
    ingredients: ['Яловичина', 'Буряк', 'Капуста', 'Картопля', 'Цибуля', 'Морква', 'Сметана', 'Пампушки'],
    isPopular: true,
    isNew: false,
    badge: 'Хіт',
  },
  {
    id: '13',
    name: 'Крем-суп з гарбуза',
    category: 'soups',
    emoji: '🎃',
    price: 115,
    oldPrice: null,
    rating: 4.6,
    reviews: 234,
    time: '10-15 хв',
    calories: 220,
    weight: '350 г',
    description: 'Оксамитовий суп-пюре з гарбуза з вершками, імбиром та насінням гарбуза.',
    ingredients: ['Гарбуз', 'Вершки', 'Імбир', 'Цибуля', 'Насіння гарбуза', 'Чебрець'],
    isPopular: false,
    isNew: false,
    badge: null,
  },

  // SALADS
  {
    id: '14',
    name: 'Цезар з куркою',
    category: 'salads',
    emoji: '🥗',
    price: 155,
    oldPrice: 180,
    rating: 4.7,
    reviews: 456,
    time: '10-15 хв',
    calories: 410,
    weight: '300 г',
    description: 'Хрусткий романо, гриль-курка, пармезан, крутони та фірмовий соус Цезар.',
    ingredients: ['Романо', 'Куряче філе', 'Пармезан', 'Крутони', 'Соус Цезар', 'Черрі'],
    isPopular: true,
    isNew: false,
    badge: null,
  },
  {
    id: '15',
    name: 'Грецький салат',
    category: 'salads',
    emoji: '🫒',
    price: 135,
    oldPrice: null,
    rating: 4.6,
    reviews: 312,
    time: '10-15 хв',
    calories: 280,
    weight: '280 г',
    description: 'Свіжі овочі, оливки каламата, сир фета та оливкова олія з лимонним соком.',
    ingredients: ['Томати черрі', 'Огірок', 'Перець', 'Оливки', 'Фета', 'Червона цибуля', 'Оливкова олія'],
    isPopular: false,
    isNew: false,
    badge: null,
  },

  // DESSERTS
  {
    id: '16',
    name: 'Тірамісу',
    category: 'desserts',
    emoji: '🍰',
    price: 125,
    oldPrice: null,
    rating: 4.9,
    reviews: 567,
    time: '5-10 хв',
    calories: 450,
    weight: '200 г',
    description: 'Класичний італійський тірамісу з маскарпоне, савояр та еспресо.',
    ingredients: ['Маскарпоне', 'Савояр', 'Еспресо', 'Яйця', 'Цукор', 'Какао'],
    isPopular: true,
    isNew: false,
    badge: 'Хіт',
  },
  {
    id: '17',
    name: 'Чізкейк Нью-Йорк',
    category: 'desserts',
    emoji: '🍮',
    price: 135,
    oldPrice: null,
    rating: 4.8,
    reviews: 423,
    time: '5-10 хв',
    calories: 490,
    weight: '180 г',
    description: 'Ніжний вершковий чізкейк на пісочній основі з ягідним кулісом.',
    ingredients: ['Вершковий сир', 'Яйця', 'Цукор', 'Пісочна основа', 'Ягідний кулі'],
    isPopular: false,
    isNew: true,
    badge: 'Новинка',
  },
  {
    id: '18',
    name: 'Шоколадний фондан',
    category: 'desserts',
    emoji: '🍫',
    price: 115,
    oldPrice: null,
    rating: 4.7,
    reviews: 334,
    time: '5-10 хв',
    calories: 520,
    weight: '160 г',
    description: 'Теплий шоколадний кекс з рідкою серединою, ванільне морозиво та малина.',
    ingredients: ['Чорний шоколад', 'Масло', 'Яйця', 'Цукор', 'Борошно', 'Морозиво'],
    isPopular: true,
    isNew: false,
    badge: null,
  },

  // DRINKS
  {
    id: '19',
    name: 'Манго Лате',
    category: 'drinks',
    emoji: '🥭',
    price: 85,
    oldPrice: null,
    rating: 4.6,
    reviews: 198,
    time: '5-10 хв',
    calories: 180,
    weight: '350 мл',
    description: 'Еспресо з манговим пюре, вершковим молоком та льодом.',
    ingredients: ['Еспресо', 'Манговe пюре', 'Молоко', 'Лід'],
    isPopular: false,
    isNew: true,
    badge: 'Новинка',
  },
  {
    id: '20',
    name: 'Лимонад Мохіто',
    category: 'drinks',
    emoji: '🍹',
    price: 75,
    oldPrice: null,
    rating: 4.7,
    reviews: 287,
    time: '5-10 хв',
    calories: 120,
    weight: '400 мл',
    description: 'Освіжаючий лимонад з м\'ятою, лаймом, лимоном та газованою водою.',
    ingredients: ['Лимон', 'Лайм', 'М\'ята', 'Цукровий сироп', 'Газована вода', 'Лід'],
    isPopular: true,
    isNew: false,
    badge: null,
  },
  {
    id: '21',
    name: 'Смузі Зелена енергія',
    category: 'drinks',
    emoji: '🥬',
    price: 95,
    oldPrice: null,
    rating: 4.5,
    reviews: 145,
    time: '5-10 хв',
    calories: 160,
    weight: '350 мл',
    description: 'Шпинат, зелене яблуко, огірок, імбир та кокосова вода.',
    ingredients: ['Шпинат', 'Зелене яблуко', 'Огірок', 'Імбир', 'Кокосова вода'],
    isPopular: false,
    isNew: false,
    badge: 'Веган',
  },
];

export const PROMO_CODES = {
  'СМАЧНО20': { discount: 20, type: 'percent', description: '20% знижка на замовлення' },
  'ПЕРШИЙ': { discount: 50, type: 'fixed', description: '50 грн знижка для нових клієнтів' },
  'ЛІТО10': { discount: 10, type: 'percent', description: '10% знижка влітку' },
};

export const DELIVERY_FEE = 45;
export const FREE_DELIVERY_THRESHOLD = 500;
